CREATE TABLE filled_order_stage (
	asset_class varchar(50) NULL,
	asset_id varchar(100) NULL,
	canceled_at varchar(50) NULL,
	client_order_id varchar(100) unique,
	created_at varchar(50) NULL,
	expired_at varchar(50) NULL,
	failed_at varchar(50) NULL,
	filled_at varchar(50),
	filled_avg_price decimal(18,2) NULL,
	filled_qty int NULL,
	id varchar(100) unique,
	limit_price varchar(10) NULL,
	order_type varchar(30) NULL,
	qty int NULL,
	side varchar(30) NULL,
	status varchar(50) NULL,
	stop_price varchar(10) NULL,
	submitted_at varchar(50) NULL,
	symbol varchar(10) NULL,
	time_in_force	varchar(20) NULL,
	type varchar(30) NULL,
	updated_at varchar(50) NULL,
    filled_at_east_std_time datetime
)
